-- INSERT INTO item VALUES (1,'apple iphone','iphone 14',799),
--                              (2,'Grocery order','Apples',10.99),
--                              (3,'Grocery order','1kg Potatoes',7.99),
--                              (4,'Electronic order','Apple macbook air m1',857),
--                              (5,'Mobile order','Redmi note 12',250),
--                              (6,'Audio device','Boat bluetooth headphones',30);

INSERT INTO categories VALUES (12,1,null,'electronics'),
                                 (13,1,null,'Grocery'),
                                 (14,1,null,'Mobiles'),
                                 (15,1,null,'Mobiles'),
                                 (16,1,null,'Home'),
                                 (17,1,null,'Appliances'),
                                 (18,2,15,'Men''s Top Wear'),
                                 (19,2,15,'Men''s Bottom Wear'),
                                 (20,2,15,'Women''s Ethnic'),
                                (21,2,12,'Audio'),
                                (22,2,12,'Electronics GST Store'),
                                (23,2,16,'Home Furnishings'),
                                (24,2,16,'Furniture Studio'),
                                (25,3,18,'All'),
                                (26,3,18,'Men''s T-shirts'),
                                (27,3,18,'Men''s casual shirts'),
                                (28,3,21,'Bluetooth Headphones'),
                                (29,3,21,'Wired Headphones');
